# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interface.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QFrame,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPlainTextEdit, QPushButton, QScrollArea, QSizePolicy,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 211, 531))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.filterStatus = QComboBox(self.frame)
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.setObjectName(u"filterStatus")
        self.filterStatus.setGeometry(QRect(10, 50, 191, 31))
        self.filterStatus.setEditable(False)
        self.filterStatus.setCurrentText(u"Tous")
        self.filterStatus.setPlaceholderText(u"")
        self.create = QPushButton(self.frame)
        self.create.setObjectName(u"create")
        self.create.setGeometry(QRect(10, 10, 191, 31))
        self.create.setStyleSheet(u"background-color:blue; color: white")
        self.scrollArea = QScrollArea(self.frame)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 90, 191, 431))
        self.scrollArea.setWidgetResizable(True)
        self.verticalLayout_1 = QWidget()
        self.verticalLayout_1.setObjectName(u"verticalLayout_1")
        self.verticalLayout_1.setGeometry(QRect(0, 0, 177, 16777215))
        self.verticalLayout_1.setMinimumSize(QSize(0, 16777215))
        self.verticalLayout_1.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayout_1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.scrollArea.setWidget(self.verticalLayout_1)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(229, 9, 561, 531))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.selectedTitle = QLineEdit(self.frame_2)
        self.selectedTitle.setObjectName(u"selectedTitle")
        self.selectedTitle.setGeometry(QRect(20, 40, 521, 41))
        font = QFont()
        font.setPointSize(20)
        self.selectedTitle.setFont(font)
        self.selectedTitle.setStyleSheet(u"")
        self.selectedTitle.setPlaceholderText(u"")
        self.selectedDescription = QPlainTextEdit(self.frame_2)
        self.selectedDescription.setObjectName(u"selectedDescription")
        self.selectedDescription.setGeometry(QRect(20, 180, 521, 81))
        self.selectedDate_3 = QLabel(self.frame_2)
        self.selectedDate_3.setObjectName(u"selectedDate_3")
        self.selectedDate_3.setGeometry(QRect(150, 110, 21, 30))
        font1 = QFont()
        font1.setPointSize(12)
        self.selectedDate_3.setFont(font1)
        self.selectedDate_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.selectedStartDate = QDateEdit(self.frame_2)
        self.selectedStartDate.setObjectName(u"selectedStartDate")
        self.selectedStartDate.setGeometry(QRect(20, 110, 116, 31))
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 90, 71, 16))
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 90, 71, 16))
        self.selectedEndDate = QDateEdit(self.frame_2)
        self.selectedEndDate.setObjectName(u"selectedEndDate")
        self.selectedEndDate.setGeometry(QRect(180, 110, 116, 31))
        self.selecteStatus = QComboBox(self.frame_2)
        self.selecteStatus.addItem("")
        self.selecteStatus.addItem("")
        self.selecteStatus.addItem("")
        self.selecteStatus.addItem("")
        self.selecteStatus.addItem("")
        self.selecteStatus.setObjectName(u"selecteStatus")
        self.selecteStatus.setGeometry(QRect(350, 110, 191, 31))
        self.selecteStatus.setEditable(False)
        self.selecteStatus.setCurrentText(u"\u00c0 faire")
        self.selecteStatus.setPlaceholderText(u"")
        self.label_3 = QLabel(self.frame_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(360, 90, 71, 16))
        self.save = QPushButton(self.frame_2)
        self.save.setObjectName(u"save")
        self.save.setGeometry(QRect(448, 493, 101, 31))
        self.save.setStyleSheet(u"background-color: green; color:white")
        self.delete_2 = QPushButton(self.frame_2)
        self.delete_2.setObjectName(u"delete_2")
        self.delete_2.setGeometry(QRect(20, 490, 101, 31))
        self.delete_2.setStyleSheet(u"background-color:red; color:white")
        self.scrollArea_2 = QScrollArea(self.frame_2)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(20, 300, 521, 171))
        self.scrollArea_2.setWidgetResizable(True)
        self.verticalLayout_2 = QWidget()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setGeometry(QRect(0, 0, 519, 16777215))
        self.verticalLayout_2.setMinimumSize(QSize(519, 16777215))
        self.verticalLayout_2.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.verticalLayout_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.createComment = QPushButton(self.verticalLayout_2)
        self.createComment.setObjectName(u"createComment")

        self.verticalLayout.addWidget(self.createComment)

        self.scrollArea_2.setWidget(self.verticalLayout_2)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 20, 161, 21))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.frame_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 160, 161, 21))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        self.label_5.setFont(font3)
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 280, 161, 21))
        self.label_6.setFont(font3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.filterStatus.setItemText(0, QCoreApplication.translate("MainWindow", u"Tous", None))
        self.filterStatus.setItemText(1, QCoreApplication.translate("MainWindow", u"\u00c0 faire", None))
        self.filterStatus.setItemText(2, QCoreApplication.translate("MainWindow", u"En cours", None))
        self.filterStatus.setItemText(3, QCoreApplication.translate("MainWindow", u"R\u00e9alis\u00e9", None))
        self.filterStatus.setItemText(4, QCoreApplication.translate("MainWindow", u"Abandonn\u00e9", None))
        self.filterStatus.setItemText(5, QCoreApplication.translate("MainWindow", u"En attente", None))

        self.create.setText(QCoreApplication.translate("MainWindow", u"Ajouter une t\u00e2che", None))
        self.selectedTitle.setText("")
        self.selectedDate_3.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Date d\u00e9but", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Date fin", None))
        self.selecteStatus.setItemText(0, QCoreApplication.translate("MainWindow", u"\u00c0 faire", None))
        self.selecteStatus.setItemText(1, QCoreApplication.translate("MainWindow", u"En cours", None))
        self.selecteStatus.setItemText(2, QCoreApplication.translate("MainWindow", u"R\u00e9alis\u00e9", None))
        self.selecteStatus.setItemText(3, QCoreApplication.translate("MainWindow", u"Abandonn\u00e9", None))
        self.selecteStatus.setItemText(4, QCoreApplication.translate("MainWindow", u"En attente", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Statut", None))
        self.save.setText(QCoreApplication.translate("MainWindow", u"Enregistrer", None))
        self.delete_2.setText(QCoreApplication.translate("MainWindow", u"Supprimer", None))
        self.createComment.setText(QCoreApplication.translate("MainWindow", u"Cr\u00e9er un commentaire", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Titre", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Commentaires", None))
    # retranslateUi

